name: lcpractice 
on: workflow_dispatch 

jobs:
  lcpractice:
    runs-on: ubuntu-latest 
    steps:
      - name: clone repository 
        run: |
          git clone https://github.com/SCULX/leetcode_practice 
          cd leetcode_practice 
      - name: install g++ make enviroment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 
      - name: run lcpractice 
        run: |
          cd leetcode_practice
          make 
      - name: test somefiles
        run: |
          ls
          6_combinationSum
          11_search
      - name: clean unused files
        run: make cleanlin