name: lcpractice 
on: workflow_dispatch 

jobs:
  lcpractice:
    runs-on: ubuntu-latest 
    steps:
      - name: clone repository 
        run: |
          git clone https://github.com/SCULX/leetcode_practice 
          cd leetcode_practice 
          ls
      - name: install g++ make enviroment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 
      - name: run lcpractice 
        run: |
          ls
          make 
