name: lcpractice 
on: workflow_dispatch 

jobs:
  lcpractice:
    runs-on: ubuntu-latest 
    steps:
      - name: clone repository 
        run: |
          git clone https://github.com/SCULX/leetcode_practice 
          cd leetcode_practice 
      - name: install g++ make enviroment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 
      - name: run lcpractice 
        run: |
          cd leetcode_practice
          make 
      # 无法进行测试，因为目前无法解决在linux安装运行exe的wine
      - name: test somefiles
        run: |
          cd leetcode_practice/mid/bin
          ls
      - name: clean unused files
        run: |
          cd leetcode_practice
          make cleanlin
          cd leetcode_practice/mid/bin
          ls
