name: lcpractice 
on: workflow_dispatch 

jobs:
  lcpractice:
    runs-on: ubuntu-latest 
    steps:
      - name: clone repository 
        run: |
          git clone https://github.com/SCULX/leetcode_practice 
          cd leetcode_practice 
      - name: install g++ make enviroment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 
      - name: run lcpractice 
        run: |
          cd leetcode_practice
          make 
     # 无法测试，因目前无法解决linux上安装wine各种问题
      - name: test somefiles
        run: |
          cd leetcode_practice
          ls
      - name: clean unused files
        run: |
          cd leetcode_practice
          make cleanlin
